FROM python:3.11.3-alpine

WORKDIR /app

RUN apk add --no-cache gcc musl-dev linux-headers

RUN pip install --upgrade pip

COPY . /app/

RUN pip install -r requirements.txt

EXPOSE 5001 

CMD ["flask", "--app", "app", "run", "--host=0.0.0.0"]
