name: Docker Image CI

# Déclencher ce workflow sur les push et les pull requests vers la branche "master"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest  # Utiliser un environnement Ubuntu

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Vérifier le dépôt GitHub

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Utilisez les secrets GitHub pour stocker les identifiants Docker Hub
        password: ${{ secrets.DOCKER_PASSWORD }}  # Ne stockez pas en clair

    - name: Build Docker Image
      run: docker build -t victory1502/myapp:latest .  # Remplacez par votre nom d'utilisateur Docker Hub et le nom de l'image

    - name: Push Docker Image to Docker Hub
      run: docker push victory1502/myapp:latest  # Pousser l'image vers Docker Hub
